# Demo-only product records. Values are fictional and intended for POC testing.

DEMO_PRODUCTS = [
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 001', 'description': 'Demo carbon black product record for warehouse scanning and inventory tracking.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226587', 'barcode': '226587', 'batch_no': 'DEMO-BC-001', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '25 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 002', 'description': 'Demo carbon black product record for warehouse scanning and inventory tracking.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226588', 'barcode': '226588', 'batch_no': 'DEMO-BC-002', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '10 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 003', 'description': 'Demo carbon black product record for warehouse scanning and inventory tracking.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226589', 'barcode': '226589', 'batch_no': 'DEMO-BC-003', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '70 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 004', 'description': 'Demo carbon black product record for warehouse scanning and inventory tracking.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226590', 'barcode': '226590', 'batch_no': 'DEMO-BC-004', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '64 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 005', 'description': 'Demo carbon black product record for warehouse scanning and inventory tracking.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226591', 'barcode': '226591', 'batch_no': 'DEMO-BC-005', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '91 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 006', 'description': 'Demo carbon black product record for warehouse scanning and inventory tracking.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226592', 'barcode': '226592', 'batch_no': 'DEMO-BC-006', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '5 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Specialty Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 007', 'description': 'Demo specialty carbon black product for QR and barcode testing.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226593', 'barcode': '226593', 'batch_no': 'DEMO-BC-007', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '50 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Specialty Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 008', 'description': 'Demo product record for barcode scanner and warehouse inventory POC.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226594', 'barcode': '226594', 'batch_no': 'DEMO-BC-008', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '21 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 009', 'description': 'Demo product record for QR scanning and automated bin assignment testing.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226595', 'barcode': '226595', 'batch_no': 'DEMO-BC-009', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '30 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 010', 'description': 'Demo product record for warehouse placement workflow testing.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226596', 'barcode': '226596', 'batch_no': 'DEMO-BC-010', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '45 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 011', 'description': 'Demo product record for inventory and QR code integration testing.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226597', 'barcode': '226597', 'batch_no': 'DEMO-BC-011', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '55 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Specialty Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 012', 'description': 'Demo product record for forklift movement and bin tracking POC.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226598', 'barcode': '226598', 'batch_no': 'DEMO-BC-012', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '60 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 013', 'description': 'Demo product record for scanner, inventory and warehouse analytics testing.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226599', 'barcode': '226599', 'batch_no': 'DEMO-BC-013', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '15 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Specialty Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 014', 'description': 'Demo product record for end-to-end QR and barcode warehouse testing.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226600', 'barcode': '226600', 'batch_no': 'DEMO-BC-014', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '80 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 015', 'description': 'Demo product record for product-to-bin mapping and inventory tracking.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226601', 'barcode': '226601', 'batch_no': 'DEMO-BC-015', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '35 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 016', 'description': 'Demo product record for live warehouse dashboard integration testing.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226602', 'barcode': '226602', 'batch_no': 'DEMO-BC-016', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '42 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Specialty Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 017', 'description': 'Demo product record for barcode scanning and forklift placement testing.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226603', 'barcode': '226603', 'batch_no': 'DEMO-BC-017', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '75 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 018', 'description': 'Demo product record for UWB-assisted warehouse location tracking.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226604', 'barcode': '226604', 'batch_no': 'DEMO-BC-018', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '90 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 019', 'description': 'Demo product record for warehouse QR scanning and stock movement testing.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226605', 'barcode': '226605', 'batch_no': 'DEMO-BC-019', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '100 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Specialty Carbon Black'},
    {'brand_name': 'Birla Carbon', 'product_name': 'Birla Carbon Sample Product 020', 'description': 'Demo product record for final end-to-end warehouse management demonstration.', 'manufactured_by': 'Birla Carbon', 'product_reference': '226606', 'barcode': '226606', 'batch_no': 'DEMO-BC-020', 'mfg_date': 'September 2026', 'exp_date': 'N/A', 'mrp': 'N/A', 'net_weight': '65 kg', 'website': 'https://www.birlacarbon.com/', 'location': 'Warehouse POC', 'category': 'Carbon Black'},
]
